@startuml DiagramaPaquetes
top to bottom direction

package "Presentacion" {
    class UsuarioControlador 
    class MedicoControlador
    class AdministradorControlador
    class EnfermeraControlador
    class PacienteControlador
    class LugarControlador
    class CitaControlador
    class HistoriaClinicaControlador
    class ProcedimientoControlador
}

package "Servicio"{
    class UsuarioServicio
    class MedicoServicio
    class AdministradorServicio
    class EnfermeraServicio
    class PacienteServicio
    class LugarServicio
    class CitaServicio
    class HistoriaClinicaServicio
    class ProcedimientoServicio
}

package "Persistencia"{
    class UsuarioRepositorio
    class MedicoRepositorio
    class AdministradorRepositorio
    class EnfermeraRepositorio
    class PacienteRepositorio
    class LugarRepositorio
    class CitaRepositorio
    class HistoriaClinicaRepositorio
    class ProcedimientoRepositorio
}

package "Modelo"{
    class Usuario
    class Medico
    class Administrador
    class Enfermera
    class Paciente
    class Lugar
    class Cita
    class HistoriaClinica
    class Procedimiento
}

package EstructuraDatos{
    interface InterLista
    class ListaEsp
    class Nodo
}

Presentacion ....> Servicio : "usa"
Presentacion ....> EstructuraDatos : "usa"

Servicio ....> Persistencia : "usa"
Servicio ....> EstructuraDatos : "usa"

Persistencia ....> Modelo : "usa"
Persistencia ....> EstructuraDatos : "usa"

'Relaciones de herencia'

Usuario <|-down- Medico
Usuario <|-down- Administrador
Usuario <|-down- Enfermera
Usuario <|-down- Paciente


'Relaciones de cardinalidad

Paciente *-- HistoriaClinica
Paciente *-- Cita
Cita o-- Lugar
Procedimiento -up-o Cita

Medico "*" --o "*" Cita : Atiende
Enfermera "*" --o "*" Cita : Asiste

ListaEsp ..|> InterLista: Implementa
ListaEsp "1" -- "1" Nodo


@enduml
