@startuml  

left to right direction

rectangle Gestionar_Citas{

    usecase "Mostrar disponibilidad\n en tiempo real" as UC_Disponibilidad 
    usecase "Agendar cita" as UC_AgendarCita 
    usecase "Editar cita" as UC_EditarCita 
    usecase "Consultar agenda de citas" as UC_AgendaMedico 
    usecase "Confirmar asistencia" as UC_ConfirmarAsistencia  
    usecase "Visualizar Cita" as UC_VerCita    
    usecase "Buscar Cita" as UC_BuscarCita
}

actor "Administrativo" as Administrativo 
actor "Médico" as Medico 
actor "Paciente" as Paciente 
actor "Enfermero" as Enfermero  

Paciente -- UC_AgendarCita
Paciente -- UC_ConfirmarAsistencia
Paciente -- UC_BuscarCita

Administrativo -- UC_AgendarCita 
Administrativo -- UC_BuscarCita

Medico -up- UC_AgendaMedico
Medico -up- UC_BuscarCita

Enfermero -up- UC_AgendaMedico
Enfermero -up- UC_BuscarCita

UC_AgendarCita .> UC_Disponibilidad : Includes

UC_EditarCita .down.> UC_BuscarCita : Extends
UC_VerCita ..>  UC_BuscarCita: Extends
@enduml 